version: '3.4'

####################
####################
services:
  ####################
  # FC-EXPLOITATION
  ####################
  exploitation-fca-low:
    hostname: exploitation-fca-low
    image: ${FC_DOCKER_REGISTRY}/nodejs:${NODE_VERSION}-dev
    user: ${CURRENT_UID}
    working_dir: /var/www/app/fc-exploitation
    depends_on:
      - 'pg-exploitation-fca-low' # pg-exploit-fca-low
      - 'mongo-fca-low'
      - 'squid'
      - 'broker'
    volumes:
      - '${VOLUMES_DIR}/src/fc-apps:/var/www/app'
      - '${VOLUMES_DIR}/app:/opt/scripts'
      - '${VOLUMES_DIR}/.home:/home'
      - '${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro'
    env_file:
      - '${COMPOSE_DIR}/shared/.env/base-app.env'
      - '${COMPOSE_DIR}/shared/.env/postgres.env'
      - '${COMPOSE_DIR}/shared/.env/fc-mongo.env'
      - '${COMPOSE_DIR}/fca-low/.env/exploitation-fca-low.env'
    networks:
      - exploitation
      - data
    command: 'tail -f /dev/null'
