version: "2.4"

####################
####################
services:
  pg-exploitation-fca-low:
    image: postgres:11
    environment:
      - "POSTGRES_DB=pg-db"
      - "POSTGRES_USER=pg-user"
      - "POSTGRES_PASSWORD=pg-password"
    networks:
      - data
