services:
  command-runner:
    hostname: command-runner
    image: "${FC_DOCKER_REGISTRY}/nodejs-apps/command-runner:test"
    user: ${CURRENT_UID}
    working_dir: /var/www/app
    volumes:
      - "${VOLUMES_DIR}/log:/data/log/app"
      - "${VOLUMES_DIR}/.home:/home"
      - "${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro"
    env_file:
      - "${COMPOSE_DIR}/shared/.env/base-app.env"
      - "${COMPOSE_DIR}/command-runner/.env/command-runner.env"
    networks:
      - data
    init: true
