services:
  command-runner:
    hostname: command-runner
    image: ${FC_DOCKER_REGISTRY}/nodejs:${NODE_VERSION}-dev
    user: ${CURRENT_UID}
    working_dir: /var/www/app
    volumes:
      - "${VOLUMES_DIR}/src/fc/back:/var/www/app"
      - "${VOLUMES_DIR}/log:/var/log/app"
      - "${VOLUMES_DIR}/.home:/home"
      - "${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro"
    env_file:
      - "${COMPOSE_DIR}/shared/.env/base-app.env"
    networks:
      - data
    init: true
    command: "pm2 logs"

  command-import-sp-sandbox:
    hostname: command-import-sp-sandbox
    image: ${FC_DOCKER_REGISTRY}/nodejs:${NODE_VERSION}-dev
    user: ${CURRENT_UID}
    working_dir: /var/www/app
    volumes:
      - "${VOLUMES_DIR}/src/fc/back:/var/www/app"
      - "${VOLUMES_DIR}/log:/var/log/app"
      - "${VOLUMES_DIR}/.home:/home"
      - "${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro"
      - "${VOLUMES_DIR}/partners/import-sandbox:/var/data:ro"
    env_file:
      - "${COMPOSE_DIR}/shared/.env/base-app.env"
      - "${COMPOSE_DIR}/command-runner/.env/command-import-sp-sandbox.env"
    networks:
      - public
      - data
    init: true
    command: "pm2 logs"
