version: '2.4'

####################
####################
services:
  partners-fca-back:
    hostname: partners-fca-back
    image: ${FC_DOCKER_REGISTRY}/nodejs:${NODE_VERSION}-dev
    user: ${CURRENT_UID}
    working_dir: /var/www/app
    depends_on:
      - "squid"
      - "redis-pwd"
      - postgres
    volumes:
      - "${VOLUMES_DIR}/src/fc/back:/var/www/app"
      - "${VOLUMES_DIR}/app:/opt/scripts"
      - "${VOLUMES_DIR}/log:/var/log/app"
      - "${VOLUMES_DIR}/.home:/home"
      - "${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro"
    env_file:
      - "${COMPOSE_DIR}/shared/.env/base-app.env"
      - "${COMPOSE_DIR}/partners-fca/.env/back.env"
    ports:
      - "10254:3001"
    networks:
      - public
      - data
    command: "pm2 logs"

  partners-fca-front:
    hostname: partners-fca-front
    image: ${FC_DOCKER_REGISTRY}/nodejs:${NODE_VERSION}-dev
    user: ${CURRENT_UID}
    working_dir: /var/www/app
    depends_on:
      - "partners-fca-back"
    volumes:
      - "${VOLUMES_DIR}/src/fc/front:/var/www/app"
      - "${VOLUMES_DIR}/app:/opt/scripts"
      - "${VOLUMES_DIR}/log:/var/log/app"
      - "${VOLUMES_DIR}/.home:/home"
      - "${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro"
    env_file:
      - "${COMPOSE_DIR}/shared/.env/base-app.env"
      - "${COMPOSE_DIR}/partners-fca/.env/front.env"
    networks:
      - fc
    command: "pm2 logs"

  partners-fca:
    image: alpine
    depends_on:
      - "partners-fca-front"
