version: '3.4'

####################
####################
services:
  exploit-fcp-high-back:
    hostname: exploit-fcp-high-back
    image: ${FC_DOCKER_REGISTRY}/nodejs:${NODE_VERSION}-dev
    user: ${CURRENT_UID}
    working_dir: /var/www/app
    depends_on:
      - 'pg-exploit-fcp-high'
      - 'mongo-fcp-high'
      - 'squid'
      - 'rnipp'
      - 'redis-pwd'
      - 'exploit-fcp-high-fi-mock'
    volumes:
      - '${VOLUMES_DIR}/src/fc/back:/var/www/app'
      - '${VOLUMES_DIR}/app:/opt/scripts'
      - '${VOLUMES_DIR}/.home:/home'
      - '${VOLUMES_DIR}/log:/var/log/app'
      - '${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro'
    env_file:
      - '${COMPOSE_DIR}/shared/.env/base-app.env'
      - '${COMPOSE_DIR}/shared/.env/postgres.env'
      - '${COMPOSE_DIR}/shared/.env/fc-mongo.env'
      - '${COMPOSE_DIR}/fcp-high/.env/exploit/back.env'
    ports:
      - 9247:9247
    networks:
      - exploitation
      - data
    command: 'tail -f /dev/null'

  exploit-fcp-high-front:
    hostname: exploit-fcp-high-front
    image: ${FC_DOCKER_REGISTRY}/nodejs:${NODE_VERSION}-dev
    user: ${CURRENT_UID}
    working_dir: /var/www/app
    depends_on:
      - 'squid'
      - 'exploit-fcp-high-back'
    volumes:
      - '${VOLUMES_DIR}/src/fc/front:/var/www/app'
      - '${VOLUMES_DIR}/app:/opt/scripts'
      - '${VOLUMES_DIR}/log:/var/log/app'
      - '${VOLUMES_DIR}/.home:/home'
      - '${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro'
    env_file:
      - '${COMPOSE_DIR}/shared/.env/base-app.env'
      - '${COMPOSE_DIR}/fcp-high/.env/exploit/front.env'
    networks:
      - exploitation
      - data
    command: 'tail -f /dev/null'
